version: "3.9"
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    image: go-app:latest
    ports:
      - "80:80"
    restart: always
    networks:
      - web

networks:
  web: